
package com.handisala.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HandisalaPortType", targetNamespace = "http://webservice.handisala.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HandisalaPortType {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "greetings", targetNamespace = "http://webservice.handisala.com")
    @RequestWrapper(localName = "postReciepe", targetNamespace = "http://webservice.handisala.com", className = "com.handisala.stub.PostReciepe")
    @ResponseWrapper(localName = "postReciepeResponse", targetNamespace = "http://webservice.handisala.com", className = "com.handisala.stub.PostReciepeResponse")
    @Action(input = "http://webservice.handisala.com/HandisalaPortType/postReciepeRequest", output = "http://webservice.handisala.com/HandisalaPortType/postReciepeResponse")
    public String postReciepe(
        @WebParam(name = "name", targetNamespace = "http://webservice.handisala.com")
        String name);

}
