
package com.handisala.stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HandisalaService", targetNamespace = "http://webservice.handisala.com", wsdlLocation = "http://chandra-pc:8080/Handisala/HandisalaService?wsdl")
public class HandisalaService
    extends Service
{

    private final static URL HANDISALASERVICE_WSDL_LOCATION;
    private final static WebServiceException HANDISALASERVICE_EXCEPTION;
    private final static QName HANDISALASERVICE_QNAME = new QName("http://webservice.handisala.com", "HandisalaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://chandra-pc:8080/Handisala/HandisalaService?wsdl");
        		} catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HANDISALASERVICE_WSDL_LOCATION = url;
        HANDISALASERVICE_EXCEPTION = e;
    }

    public HandisalaService() {
        super(__getWsdlLocation(), HANDISALASERVICE_QNAME);
    }

    public HandisalaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HANDISALASERVICE_QNAME, features);
    }

    public HandisalaService(URL wsdlLocation) {
        super(wsdlLocation, HANDISALASERVICE_QNAME);
    }

    public HandisalaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HANDISALASERVICE_QNAME, features);
    }

    public HandisalaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HandisalaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HandisalaPortType
     */
    @WebEndpoint(name = "HandisalaPortTypePort")
    public HandisalaPortType getHandisalaPortTypePort() {
        return super.getPort(new QName("http://webservice.handisala.com", "HandisalaPortTypePort"), HandisalaPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HandisalaPortType
     */
    @WebEndpoint(name = "HandisalaPortTypePort")
    public HandisalaPortType getHandisalaPortTypePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.handisala.com", "HandisalaPortTypePort"), HandisalaPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HANDISALASERVICE_EXCEPTION!= null) {
            throw HANDISALASERVICE_EXCEPTION;
        }
        return HANDISALASERVICE_WSDL_LOCATION;
    }

}
